name: food_ordering_project
services:
  customer_frontend:
    image: nathapatt/ordering-food-customer
    container_name: food_ordering_customer_frontend
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - VITE_NGINX_PROXY=${VITE_NGINX_PROXY}
    ports:
      - '${PORT}:80'
    networks:
      - food_ordering_project_food_ordering_network
    restart: unless-stopped

networks:
  food_ordering_project_food_ordering_network:
    external: true